//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 01:59:57 PM CEST 
//

package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naziv">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Uvodni_deo" type="{}Uvodni_deo"/>
 *         &lt;element name="Glavni_deo" type="{}Glavni_deo"/>
 *         &lt;element name="Zavrsni_deo" type="{}Zavrsni_deo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "naziv", "uvodniDeo", "glavniDeo", "zavrsniDeo" })
@XmlRootElement(name = "Akt")
@Entity
@Table(name = "akt")
public class Akt {

	@Id
	@GeneratedValue
	@Column(name = "akt_id")
	private Integer id;

	@XmlElement(name = "Naziv", required = true)
	protected String naziv;
	@XmlElement(name = "Uvodni_deo", required = true)
	@OneToOne
	@JoinColumn(name="uvodni_deo_id")
	private UvodniDeo uvodniDeo;
//	@XmlElement(name = "Glavni_deo", required = true)
//    @OneToOne
//	@JoinColumn(name="glavni_deo_id")
//	 protected GlavniDeo glavniDeo;
	// @XmlElement(name = "Zavrsni_deo", required = true)
	// //@OneToOne(mappedBy="akt", cascade=CascadeType.ALL)
	// protected ZavrsniDeo zavrsniDeo;

	/**
	 * Gets the value of the naziv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNaziv() {
		return naziv;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Akt() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * Sets the value of the naziv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNaziv(String value) {
		this.naziv = value;
	}

	/**
	 * Gets the value of the uvodniDeo property.
	 * 
	 * @return possible object is {@link UvodniDeo }
	 * 
	 */
	public UvodniDeo getUvodniDeo() {
		return uvodniDeo;
	}

	/**
	 * Sets the value of the uvodniDeo property.
	 * 
	 * @param value
	 *            allowed object is {@link UvodniDeo }
	 * 
	 */
	public void setUvodniDeo(UvodniDeo value) {
		this.uvodniDeo = value;
	}

	/**
	 * Gets the value of the glavniDeo property.
	 * 
	 * @return possible object is {@link GlavniDeo }
	 * 
	 */
	// public GlavniDeo getGlavniDeo() {
	// return glavniDeo;
	// }
	//
	// /**
	// * Sets the value of the glavniDeo property.
	// *
	// * @param value
	// * allowed object is
	// * {@link GlavniDeo }
	// *
	// */
	// public void setGlavniDeo(GlavniDeo value) {
	// this.glavniDeo = value;
	// }
	//
	// /**
	// * Gets the value of the zavrsniDeo property.
	// *
	// * @return
	// * possible object is
	// * {@link ZavrsniDeo }
	// *
	// */
	// public ZavrsniDeo getZavrsniDeo() {
	// return zavrsniDeo;
	// }
	//
	// /**
	// * Sets the value of the zavrsniDeo property.
	// *
	// * @param value
	// * allowed object is
	// * {@link ZavrsniDeo }
	// *
	// */
	// public void setZavrsniDeo(ZavrsniDeo value) {
	// this.zavrsniDeo = value;
	// }

}
