//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 01:59:57 PM CEST 
//


package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Kaznjiva_radnja_i_sankcija complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Kaznjiva_radnja_i_sankcija">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Kaznjiva_radnja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sankcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kaznjiva_radnja_i_sankcija", propOrder = {
    "kaznjivaRadnja",
    "sankcija"
})
@Entity
@Table(name = "kaznjiva_radnja_i_sankcija")
public class KaznjivaRadnjaISankcija {
	
	@Id
	@Column(name = "kaznjiva_radnja_i_sankcija_id")
	@GeneratedValue
	private Integer id;

    @XmlElement(name = "Kaznjiva_radnja", required = true)
    protected String kaznjivaRadnja;
    @XmlElement(name = "Sankcija", required = true)
    protected String sankcija;

    /**
     * Gets the value of the kaznjivaRadnja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKaznjivaRadnja() {
        return kaznjivaRadnja;
    }

    /**
     * Sets the value of the kaznjivaRadnja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKaznjivaRadnja(String value) {
        this.kaznjivaRadnja = value;
    }

    /**
     * Gets the value of the sankcija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSankcija() {
        return sankcija;
    }

    /**
     * Sets the value of the sankcija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSankcija(String value) {
        this.sankcija = value;
    }

}
