//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 01:59:57 PM CEST 
//


package model;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * <p>Java class for Kaznena_odredba complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Kaznena_odredba">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Propis">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Norma" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Naredjujuca_norma"/>
 *                         &lt;enumeration value="Zabranjujuca_norma"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Kaznjiva_radnja_i_sankcija" type="{}Kaznjiva_radnja_i_sankcija" maxOccurs="unbounded"/>
 *         &lt;element name="Bice_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Subjekt_odgovornosti" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kaznena_odredba", propOrder = {
    "propis",
    "kaznjivaRadnjaISankcija",
    "biceDela",
    "subjektOdgovornosti"
})
@Entity
@Table(name = "kaznena_odredba")
public class KaznenaOdredba {
	
	@Id
	@GeneratedValue
	@Column(name = "kaznena_odredba_id")
	private Integer id;
	
	
	@XmlElement(name = "Norma", required = true)
	@ElementCollection(fetch = FetchType.EAGER)
	@CollectionTable(name = "norma", joinColumns = @JoinColumn(name = "kaznena_odredba_id"))
	@Column(name = "definicija")
	protected List<String> norma;

  
    
    @XmlElement(name = "Kaznjiva_radnja_i_sankcija", required = true)
//    @OneToMany(cascade={CascadeType.ALL})
//    @JoinColumn(name="kaznena_odredba_id")
    @OneToMany(mappedBy="kaznenaOdredba",fetch = FetchType.EAGER)
    protected Set<KaznjivaRadnjaISankcija> kaznjivaRadnjaISankcija;
   
    @XmlElement(name = "Bice_dela", required = true)
    protected String biceDela;
    @XmlElement(name = "Subjekt_odgovornosti", required = true)
    protected String subjektOdgovornosti;

    @ManyToOne
	@JoinColumn(name = "glavni_deo_id", referencedColumnName = "glavni_deo_id", nullable = false)
    @JsonIgnore
	private GlavniDeo glavniDeo;
    
    /**
     * Gets the value of the propis property.
     * 
     * @return
     *     possible object is
     *     {@link KaznenaOdredba.Propis }
     *     
     */
   

    /**
     * Sets the value of the propis property.
     * 
     * @param value
     *     allowed object is
     *     {@link KaznenaOdredba.Propis }
     *     
     */
   

    /**
     * Gets the value of the kaznjivaRadnjaISankcija property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kaznjivaRadnjaISankcija property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKaznjivaRadnjaISankcija().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KaznjivaRadnjaISankcija }
     * 
     * 
     */
    public Set<KaznjivaRadnjaISankcija> getKaznjivaRadnjaISankcija() {
        if (kaznjivaRadnjaISankcija == null) {
            kaznjivaRadnjaISankcija = new HashSet<KaznjivaRadnjaISankcija>();
        }
        return this.kaznjivaRadnjaISankcija;
    }

    /**
     * Gets the value of the biceDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiceDela() {
        return biceDela;
    }

    /**
     * Sets the value of the biceDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiceDela(String value) {
        this.biceDela = value;
    }

    /**
     * Gets the value of the subjektOdgovornosti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjektOdgovornosti() {
        return subjektOdgovornosti;
    }

    /**
     * Sets the value of the subjektOdgovornosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjektOdgovornosti(String value) {
        this.subjektOdgovornosti = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Norma" maxOccurs="unbounded">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Naredjujuca_norma"/>
     *               &lt;enumeration value="Zabranjujuca_norma"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
   
    
   

        

      
        public List<String> getNorma() {
            if (norma == null) {
                norma = new ArrayList<String>();
            }
            return this.norma;
        }

    

}
