//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 01:59:57 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KaznenaOdredba }
     * 
     */
    public KaznenaOdredba createKaznenaOdredba() {
        return new KaznenaOdredba();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link UvodniDeo }
     * 
     */
    public UvodniDeo createUvodniDeo() {
        return new UvodniDeo();
    }

    /**
     * Create an instance of {@link GlavniDeo }
     * 
     */
    public GlavniDeo createGlavniDeo() {
        return new GlavniDeo();
    }

    /**
     * Create an instance of {@link ZavrsniDeo }
     * 
     */
    public ZavrsniDeo createZavrsniDeo() {
        return new ZavrsniDeo();
    }

    /**
     * Create an instance of {@link Ovlascenje }
     * 
     */
    public Ovlascenje createOvlascenje() {
        return new Ovlascenje();
    }

    /**
     * Create an instance of {@link KaznjivaRadnjaISankcija }
     * 
     */
    public KaznjivaRadnjaISankcija createKaznjivaRadnjaISankcija() {
        return new KaznjivaRadnjaISankcija();
    }

    /**
     * Create an instance of {@link KaznenaOdredba.Propis }
     * 
     */
    public KaznenaOdredba.Propis createKaznenaOdredbaPropis() {
        return new KaznenaOdredba.Propis();
    }

}
