//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 01:59:57 PM CEST 
//


package model;

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ovlascenje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ovlascenje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ovlasceni_organ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Obim" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Period_vazenja" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ovlascenje", propOrder = {
    "ovlasceniOrgan",
    "obim",
    "periodVazenja"
})
public class Ovlascenje {

	@Id
	@Column(name = "ovlascenje_id")
	@GeneratedValue
	private Integer id;
	
    @XmlElement(name = "Ovlasceni_organ", required = true)
    protected String ovlasceniOrgan;
    @XmlElement(name = "Obim", required = true)
    protected String obim;
    @XmlElement(name = "Period_vazenja", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger periodVazenja;

    @ManyToOne
	@JoinColumn(name = "glavni_deo_id", referencedColumnName = "glavni_deo_id", nullable = false)
	private GlavniDeo glavniDeo;
    /**
     * Gets the value of the ovlasceniOrgan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvlasceniOrgan() {
        return ovlasceniOrgan;
    }

    /**
     * Sets the value of the ovlasceniOrgan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvlasceniOrgan(String value) {
        this.ovlasceniOrgan = value;
    }

    /**
     * Gets the value of the obim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObim() {
        return obim;
    }

    /**
     * Sets the value of the obim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObim(String value) {
        this.obim = value;
    }

    /**
     * Gets the value of the periodVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeriodVazenja() {
        return periodVazenja;
    }

    /**
     * Sets the value of the periodVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriodVazenja(BigInteger value) {
        this.periodVazenja = value;
    }

}
