//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.11 at 06:39:49 PM CEST 
//


package model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Clan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Upit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DatumPredloga" type="{http://www.w3.org/2001/XMLSchema}Date" minOccurs="0"/>
 *         &lt;element name="DatumUsvajanja" type="{http://www.w3.org/2001/XMLSchema}Date" minOccurs="0"/>
 *         &lt;element name="Predlagac" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Upit", propOrder = {
    "id",
    "naziv",
    "status",
    "datumPredloga", 
    "datumUsvajanja",
    "predlagac"
})
public class Upit {

    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "Naziv")
    protected String naziv;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "DatumPredloga")
    protected Date  datumPredloga;
    @XmlElement(name = "DatumUsvajanja")
    protected Date  datumUsvajanja;
    @XmlElement(name = "Predlagac")
    protected String predlagac;
    
    
    
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	
	
	
	public String getNaziv() {
		return naziv;
	}
	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}
	
	
	
	
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
	
	
	
	public Date getDatumPredloga() {
		return datumPredloga;
	}
	public void setDatumPredloga(Date datumPredloga) {
		this.datumPredloga = datumPredloga;
	}
	
	
	
	
	public Date getDatumUsvajanja() {
		return datumUsvajanja;
	}
	public void setDatumUsvajanja(Date datumUsvajanja) {
		this.datumUsvajanja = datumUsvajanja;
	}
	
	
	
	
	public String getPredlagac() {
		return predlagac;
	}
	public void setPredlagac(String predlagac) {
		this.predlagac = predlagac;
	}




}
