//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 01:59:57 PM CEST 
//


package model;

import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Zavrsni_deo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zavrsni_deo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prelazne_odredbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Zavrsne_odredbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="datum" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="broj_propisa" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zavrsni_deo", propOrder = {
    "prelazneOdredbe",
    "zavrsneOdredbe"
})
@Entity
@Table(name = "zavrsni_deo")

public class ZavrsniDeo {
	
	@Id
	@Column (name = "zavrsni_deo_id")
	@GeneratedValue
	private Integer id;
	
    @XmlElement(name = "Prelazne_odredbe", required = true)
    protected String prelazneOdredbe;
    
    @XmlElement(name = "Zavrsne_odredbe", required = true)
    protected String zavrsneOdredbe;
    
    @XmlAttribute(name = "datum", required = true)
    @XmlSchemaType(name = "date")
    protected Date datum;
    
    @XmlAttribute(name = "broj_propisa", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPropisa;

    /**
     * Gets the value of the prelazneOdredbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrelazneOdredbe() {
        return prelazneOdredbe;
    }

    /**
     * Sets the value of the prelazneOdredbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrelazneOdredbe(String value) {
        this.prelazneOdredbe = value;
    }

    /**
     * Gets the value of the zavrsneOdredbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZavrsneOdredbe() {
        return zavrsneOdredbe;
    }

    /**
     * Sets the value of the zavrsneOdredbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZavrsneOdredbe(String value) {
        this.zavrsneOdredbe = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(Date value) {
        this.datum = value;
    }

    /**
     * Gets the value of the brojPropisa property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPropisa() {
        return brojPropisa;
    }

    /**
     * Sets the value of the brojPropisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPropisa(BigInteger value) {
        this.brojPropisa = value;
    }

}
