//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.11 at 06:39:49 PM CEST 
//


package model.view;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Clan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Upit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DatumPredloga" type="{http://www.w3.org/2001/XMLSchema}Date" minOccurs="0"/>
 *         &lt;element name="DatumUsvajanja" type="{http://www.w3.org/2001/XMLSchema}Date" minOccurs="0"/>
 *         &lt;element name="Predlagac" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Upit", propOrder = {
    "id",
    "naziv",
    "status",
    "datumPredlogaOd", 
    "datumPredlogaDo",
    "datumUsvajanja",
    "predlagac"
})
public class Upit {

    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "Naziv")
    protected String naziv;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "DatumPredlogaOd")
    protected Date  datumPredlogaOd;
    @XmlElement(name = "DatumPredlogaDo")
    protected Date  datumPredlogaDo;
    @XmlElement(name = "DatumUsvajanja")
    protected Date  datumUsvajanja;
    @XmlElement(name = "Predlagac")
    protected String predlagac;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getNaziv() {
		return naziv;
	}
	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public Date getDatumPredlogaOd() {
		return datumPredlogaOd;
	}
	public void setDatumPredlogaOd(Date datumPredlogaOd) {
		this.datumPredlogaOd = datumPredlogaOd;
	}
	public Date getDatumPredlogaDo() {
		return datumPredlogaDo;
	}
	public void setDatumPredlogaDo(Date datumPredlogaDo) {
		this.datumPredlogaDo = datumPredlogaDo;
	}
	public Date getDatumUsvajanja() {
		return datumUsvajanja;
	}
	public void setDatumUsvajanja(Date datumUsvajanja) {
		this.datumUsvajanja = datumUsvajanja;
	}
	public String getPredlagac() {
		return predlagac;
	}
	public void setPredlagac(String predlagac) {
		this.predlagac = predlagac;
	}
	public Upit(String id, String naziv, String status, Date datumPredlogaOd, Date datumPredlogaDo, Date datumUsvajanja,
			String predlagac) {
		super();
		this.id = id;
		this.naziv = naziv;
		this.status = status;
		this.datumPredlogaOd = datumPredlogaOd;
		this.datumPredlogaDo = datumPredlogaDo;
		this.datumUsvajanja = datumUsvajanja;
		this.predlagac = predlagac;
	}
	public Upit() {
		super();
		// TODO Auto-generated constructor stub
	}
    
    
    


}
