//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 12:00:31 AM CEST 
//


package model.amandman;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NazivAmandmana.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NazivAmandmana">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Propis o izmeni"/>
 *     &lt;enumeration value="Propis o dopuni"/>
 *     &lt;enumeration value="Propis o izmeni i dopunama"/>
 *     &lt;enumeration value="Propis o izmenama i dopuni"/>
 *     &lt;enumeration value="Propis o izmenama i dopunama"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NazivAmandmana")
@XmlEnum
public enum NazivAmandmana {

    @XmlEnumValue("Propis o izmeni")
    PROPIS_O_IZMENI("Propis o izmeni"),
    @XmlEnumValue("Propis o dopuni")
    PROPIS_O_DOPUNI("Propis o dopuni"),
    @XmlEnumValue("Propis o izmeni i dopunama")
    PROPIS_O_IZMENI_I_DOPUNAMA("Propis o izmeni i dopunama"),
    @XmlEnumValue("Propis o izmenama i dopuni")
    PROPIS_O_IZMENAMA_I_DOPUNI("Propis o izmenama i dopuni"),
    @XmlEnumValue("Propis o izmenama i dopunama")
    PROPIS_O_IZMENAMA_I_DOPUNAMA("Propis o izmenama i dopunama");
    private final String value;

    NazivAmandmana(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NazivAmandmana fromValue(String v) {
        for (NazivAmandmana c: NazivAmandmana.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
