//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 12:00:31 AM CEST 
//


package model.amandman;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Referenca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Referenca">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="clan_ref" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="stav_ref" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="tacka_ref" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Referenca", propOrder = {
    "content"
})
public class Referenca {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "clan_ref")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger clanRef;
    @XmlAttribute(name = "stav_ref")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger stavRef;
    @XmlAttribute(name = "tacka_ref")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger tackaRef;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the clanRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClanRef() {
        return clanRef;
    }

    /**
     * Sets the value of the clanRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClanRef(BigInteger value) {
        this.clanRef = value;
    }

    /**
     * Gets the value of the stavRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStavRef() {
        return stavRef;
    }

    /**
     * Sets the value of the stavRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStavRef(BigInteger value) {
        this.stavRef = value;
    }

    /**
     * Gets the value of the tackaRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTackaRef() {
        return tackaRef;
    }

    /**
     * Sets the value of the tackaRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTackaRef(BigInteger value) {
        this.tackaRef = value;
    }

}
